apiVersion: v1
kind: Service
metadata:
  name: e2e-tutorial-service
  labels:
    app: e2e-tutorial
spec:
  type: NodePort
  selector:
    app: e2e-tutorial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080